### ISSUE TITLE
Update for Solid Edge ST10

### ISSUE THREAD

**Issue by nemler** [SolidEdgeCommunity/Interop.SolidEdge#2]
The Interop needs to be updated to Solid Edge ST10.

**Comment by CrapuleJack** [comment]
I would also need to get this package updated for the latest ST10 release, I have some customers waiting for that, thanks.

**Comment by jlnewell** [comment]
My apologies for letting it get behind. I am not currently doing any active Solid Edge development but I did get Solid Edge installed back on my machine last night with the intention on getting this updated. Should have it out later tonight.

**Comment by CrapuleJack** [comment]
Many thanks for the prompt response 😎 

Crapulaphone

**Comment by jlnewell** [comment]
Quick question @nemler & @CrapuleJack. Are you only interested in getting Interop.SolidEdge updated? I'm wondering about the future of SolidEdge.Community & SolidEdge.Community.AddIn since I'm not active anymore.

**Comment by CrapuleJack** [comment]
I personally only need the Interop.SolidEdge part, thanks.

**Comment by jlnewell** [comment]
I got the ST9 MP packages updated. I paused on the ST10 package release because the API has changed enough that I need to take a moment and make sure I get it right. Weekend release is now my target.

**Comment by CrapuleJack** [comment]
Thanks a lot, this is much appreciated.

**Comment by jlnewell** [comment]
Done. I took the opportunity to update the .csproj file to the latest format + added custom MSBUILD .targets file. Sure makes creating the NuGet package oh so much easier. Let me know if you run into any issues.

**Comment by jlnewell** [comment]
Closing issue.

**Comment by CrapuleJack** [comment]
Thanks a lot
