### ISSUE TITLE
Update for Solid Edge 2020

### ISSUE THREAD

**Issue by MatthiasLeemann** [SolidEdgeCommunity/Interop.SolidEdge#3]
The Interop needs to be updated to Solid Edge 2020.

I have trouble with following code:

...
propertySets.Open(file.FullName, false);
                properties = (SolidEdgeFileProperties.Properties)propertySets["ExtendedSummaryInformation"];
                property = (SolidEdgeFileProperties.Property)properties["Status"];
                property.Value = status;
                propertySets.Save();
                result = true;

...

The value don't save without error.

**Comment by MatthiasLeemann** [comment]
Thanks for the new version 220.2.0! Now i have an error, see the pdf.
[Interop Solidedge V220.2.0.pdf](https://github.com/SolidEdgeCommunity/Interop.SolidEdge/files/3939818/Interop.Solidedge.V220.2.0.pdf)

**Comment by jlnewell** [comment]
The same behavior is exhibited by referencing the Solid Edge File Properties Object Library (PropAuto.dll) directly. This implies that the issue is not related to the Interop.SolidEdge NuGet package. You will need to file an IR with Siemens GTAC to get an answer as to why they are returning TYPE_E_CANTLOADLIBRARY when you try to set the status. My suspicion is that they do not allow the status to be changed via their API.

**Comment by MatthiasLeemann** [comment]
Hello Jason
That's bad news! I find it problematic if this functionality is suddenly turned off.
I have started an urgent support request.

**Comment by pellaken** [comment]
Wonder if there is an issue with the library?  I'm getting this when I try to run a VB app:

{"Could not load file or assembly 'Interop.SolidEdgeFileProperties, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded."}

**Comment by pellaken** [comment]
Never mind, needed to specify a newer .Net version than 3.5...

Now getting an exception, but it is resetting the status on the file...

**Comment by pellaken** [comment]
I have this working in SE 2020 MP2 without error.  Note that I am not using Jason's Interop for this...

Module Module1
    Dim sepropset As SolidEdgeFileProperties.PropertySets
    Dim seprops As SolidEdgeFileProperties.Properties
    Dim sepropsNDX As SolidEdgeFileProperties.Properties
    Dim seprop As SolidEdgeFileProperties.Property
    Dim sepropNDX As SolidEdgeFileProperties.Property
    Sub Main()
        sepropset = New SolidEdgeFileProperties.PropertySets
        sepropset.Open("c:\temp\part1.par", False)
        seprops = sepropset.Item("ExtendedSummaryInformation")
        sepropsNDX = sepropset.Item("SummaryInformation")
        seprop = seprops.Item("Status")
        sepropNDX = sepropsNDX.Item("Security")
        MsgBox(seprop.Value & " - " & sepropNDX.Value)
        seprop.Value = 0
        sepropNDX.Value = 0
        sepropset.Save()
        MsgBox(seprop.Value & " - " & sepropNDX.Value)
        sepropset.Close()
        seprop = Nothing
        sepropNDX = Nothing
        seprops = Nothing
        sepropsNDX = Nothing
        sepropset = Nothing
    End Sub


End Module

**Comment by MatthiasLeemann** [comment]
I was able to fix the error. Please note, this is not an error of the PropAuto.dll but an error of Installation of my computer.

Start commandline tool and type:

regsvr32.exe "C:\Program Files\Siemens\Solid Edge 2020\Program\PropAuto.dll"

Best regards
Matthias
